FROM node:18-bullseye

WORKDIR /stockmateai-backend

RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm install --production

COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt


COPY . .

EXPOSE 3000

CMD ["node", "index.js"]